### PR TITLE
Add job to update amazon 2 in cron workflow

### PR DESCRIPTION
**Pull request by brycekahle**
Adds a job that uses the `amazonlinux:2` container to automatically update Amazon kernels. I figured out and added support to search both architectures from a single arch machine. I basically add the cross-arch repo on container setup and then search for packages using `repoquery` which supports `--archlist`.

Also fixes btfhub run commands to only use `sudo` when it is present.

This also makes a couple changes to how things are structured:

- removes `archive` and `custom-archive` directories from repo
- clones `btfhub` directly into the workspace directory
- clones `btfhub-archive` directly into the `archive` directory. This prevents the need for `rsync`-ing files around.
- adds sparse checkout of `btfhub-archive` to improve clone speeds.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
Checking this now. Sorry for the delay.

**Comment by geyslan** [comment]
@brycekahle sorry for the delay. Is this still relevant? Should I go on reviewing it?

**Comment by brycekahle** [comment]
@geyslan We are maintaining our own fork now, since we needed to add support for kernel modules. Feel free to do what you wish with this PR.

**Comment by geyslan** [comment]
@brycekahle I'm addressing a few other issues, but I'll take a closer look at this PR soon. In the meantime, can you explain why you created a new job just for Amazon?

**Comment by brycekahle** [comment]
I was unable to access the repos directly outside of Amazon Linux.

**Comment by geyslan** [comment]
@brycekahle I've got a time to go over this. I'm closing it in favour of https://github.com/aquasecurity/btfhub/pull/118.

**Pull request closed without merging**
