### PR TITLE
Add Ubuntu 16.04 (xenial)

### PR DESCRIPTION
**Pull request by brycekahle**
Goes with https://github.com/aquasecurity/btfhub-archive/pull/11

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
@brycekahle quick question, what is your use case for BTF files for such old kernels ? (4.15) ? Forgot to ask you. I'm wondering if BTF files are meaningful for kernels not supporting CO-RE (afaik).

**Comment by brycekahle** [comment]
@rafaeldtinoco BTF is useful for older kernels, since is the loader that does the entire relocation process. Only some of the newer program types (fentry, raw tracepoints) require BTF support in the kernel itself.

**Comment by brycekahle** [comment]
We have an product that supports kernels going back to 4.4 that is transitioning to using CO-RE

**Comment by rafaeldtinoco** [comment]
Ah gotcha. Yep, I'm aware of how the BTF relocations work. I wanted to know if you had a use case for those and, since you do, let's keep those for sure! Thanks for answering!

**Pull request merged**
