### PR TITLE
feat: Add bats test for update.sh

### PR DESCRIPTION
**Pull request by simar7**
**Summary:**
This PR adds tests for `update.sh` by asserting on the behaviour that BTF archives can be properly pulled and generated. 

**How to run:**
`make test`

You can see a sample run here: https://github.com/aquasecurity/btfhub/runs/4337240286?check_suite_focus=true
image

The tests will also be run on each PR as it is created.
Read more on BATS: https://bats-core.readthedocs.io/en/stable/

### CODE REVIEW

**Review by rafaeldtinoco — APPROVED** [review]
LGTM. Would you mind squashing/rebasing so it has only the needed commit ?

**Comment by simar7** [comment]
> LGTM. Would you mind squashing/rebasing so it has only the needed commit ?

Yeah I do that at merge time! 😄

**Comment by itaysk** [comment]
WDYT about adding basic sanity tests on the resulting artifacts using `bpftool`? are we interested only in the exit code or also that the file came artifact came out as expected in this test?

**Comment by simar7** [comment]
> WDYT about adding basic sanity tests on the resulting artifacts using `bpftool`? are we interested only in the exit code or also that the file came artifact came out as expected in this test?

Yeah that's the ideal place we want to be. Working towards it.

**Pull request merged**
