### PR TITLE
ubuntu: add support for azure kernels

### PR DESCRIPTION
**Pull request by alban**
My goal is to make it work for GitHub Action runs, they run with kernel 5.8.0-1041-azure.

cc @mauriciovasquezbernal

### CODE REVIEW

**Comment by alban** [comment]
The PR is not ready for being merged:
- [ ] pahole needs to use `--btf_encode_detached`
- [ ] It seems to pick a deb package without the necessary file.

**Comment by rafaeldtinoco** [comment]
> The PR is not ready for being merged:
> 
> * [ ]  pahole needs to use `--btf_encode_detached`
> * [ ]  It seems to pick a deb package without the necessary file.

You fixed the 2nd. Im fixing the first. Will rebase yours on top of the first fix. After rebased will download the kernels and generate the BTFs, uploading them to the hub. 

Tku!

**Comment by rafaeldtinoco** [comment]
@alban , just uploaded the BTF files for azure:

```
commit 6e92e54 (HEAD -> main, origin/main, origin/HEAD)
Author: Rafael David Tinoco <rafaeldtinoco@gmail.com>
Date:   Wed Sep 29 17:29:50 2021

    ubuntu: add focal azure kernel btf files

commit c2d3eb4
Author: Rafael David Tinoco <rafaeldtinoco@gmail.com>
Date:   Wed Sep 29 17:29:12 2021

    ubuntu: add bionic azure kernel btf files
```

Thanks!

**Comment by alban** [comment]
Thanks for uploading the BTF files!

It works for me on the following platforms:
* GitHub Actions
* AKS

Here is an example of snippet that can be used in `.github/workflows/test.yml`:
```
    - name: Unit tests with BTF
      run: |
        KERNEL=$(uname -r)
        ARCH=$(uname -m)
        if test -f /sys/kernel/btf/vmlinux; then
          echo "BTF is available at /sys/kernel/btf/vmlinux"
        else
          echo "BTF is not available: Trying BTFHub"
          source /etc/os-release
          URL="https://github.com/aquasecurity/btfhub/raw/main/$ID/$VERSION_ID/$ARCH/$KERNEL.btf.tar.xz"
          echo "Trying to download vmlinux from $URL"

          if [[ $(wget -S --spider "$URL" 2>&1 | grep 'HTTP/1.1 200 OK') ]]; then
            wget -q -O /tmp/vmlinux.btf.tar.xz "$URL"
            tar -xvf /tmp/vmlinux.btf.tar.xz
            # Use objcopy to put the btf info in an ELF file as libbpf and cilium/ebpf
            # by default check if there is an ELF file with the .BTF section at
            # /boot/vmlinux-$KERNEL.
            sudo objcopy --input binary --output elf64-little --rename-section .data=.BTF *.btf /boot/vmlinux-$KERNEL
            rm *.btf
            echo "vmlinux downloaded at /boot/vmlinux-$KERNEL"
          else
            echo "vmlinux not found"
          fi
        fi

        make test
```
Example of successful output:
```
BTF is not available: Trying BTFHub
Trying to download vmlinux from https://github.com/aquasecurity/btfhub/raw/main/ubuntu/20.04/x86_64/5.8.0-1042-azure.btf.tar.xz
5.8.0-1042-azure.btf
vmlinux downloaded at /boot/vmlinux-5.8.0-1042-azure
```

What about publishing a GitHub Action that could be reused without copy/paste of the snippet above?

**Pull request merged**
